### ISSUE TITLE
Good idea, but too simple thought

### ISSUE THREAD

**Issue by ikaroso** [Yao-Shao/Basketball-Game-Goal-Detector#1]
Hello. First, i must say thanks for your effort.

I am working on a project about detecting ball-carrier, predicting/recognizing the pose  of the ball-carrier.

Now, using yolov3 and some image process techniques, I have reached some achievements.

If you want to cooperate  with me or discuss anyhing about ML, CNN, CV, please go to my QQ  644386208 , or Wechat   Jacksparrowwwww

**Comment by Yao-Shao** [comment]
Wechat added, pls check:)
